name: Feature request
description: Request a new feature
title: "enhancement: "
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Documentation attestation
      description: Make sure you checked all of the below before submitting an issue
      options:
        - label: I have read all the accompanying documentation, if it exists
          required: true
  - type: dropdown
    attributes:
      label: Script selection
      description: Which script are you requesting a feature for?
      options:
        - clocktable
        - photo-helper
        - wsl2
    validations:
      required: true
  - type: textarea
    validations:
      required: true
    attributes:
      label: Describe the feature you are requesting
      description: A clear and concise description of what you want to happen.
  - type: textarea
    validations:
      required: false
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
